export const doctor_categories = [
  "IMMUNOLOGIST",
  "CARDIOLOGIST",
  "NEUROLOGIST",
  "DERMATOLOGIST",
  "ENT",
  "GASTROENTEROLOGIST",
  "GENERAL PHYSICIAN",
  "GYNAECOLOGIST",
  "INFECTIOUS DISEASE SPECIALIST",
  "NEPHROLOGIST",
  "ORTHOPAEDIC SURGEON",
  "PAEDIATRICIAN",
  "PSYCHIATRIST",
];

export const lab_tests = [
  "CBC",
  "ESR",
  "BLOOD SUGAR",
  "LIPID PROFILE",
  "LIVER FUNCTION TEST",
  "THYROID PROFILE",
  "URINE ROUTINE",
  "URINE MICROSCOPY",
  "X-RAY CHEST",
];

export const diseases = {
  CANCER: true,
  DIABETES: true,
  "HEART DISEASE": true,
  STROKE: true,
  OBESITY: true,
  DEPRESSION: false,
  "ALZHEIMER'S DISEASE": true,
  "PARKINSON'S DISEASE": true,
  ASTHMA: true,
  COPD: true,
  "CHRONIC KIDNEY DISEASE": true,
  "HIGH BLOOD PRESSURE": true,
  "HIGH CHOLESTEROL": true,
  OSTEOPOROSIS: true,
  ANXIETY: false,
  "BIPOLAR DISORDER": false,
  EPILEPSY: false,
  MIGRAINE: false,
  SCHIZOPHRENIA: false,
  "SLEEP DISORDERS": false,
  "SUBSTANCE ABUSE": false,
  TUBERCULOSIS: true,
  "HIV/AIDS": true,
  HYPERTENSION: true,
  MALARIA: false,
  TYPHOID: false,
  DIARRHOEA: false,
  CHOLERA: false,
  HEPATITIS: false,
  MENINGITIS: false,
  MUMPS: false,
  RABIES: false,
  FEVER: false,
  "COMMON COLD": false,
  "FLU (INFLUENZA)": false,
  "ALLERGIC RHINITIS": false,
  "ACUTE BRONCHITIS": false,
};

export const times = {
  0: "9:00 AM to 9.30 AM",
  1: "9:30 AM to 10.00 AM",
  2: "10:00 AM to 10.30 AM",
  3: "10:30 AM to 11.00 AM",
  4: "11:00 AM to 11.30 AM",
  5: "11:30 AM to 12.00 PM",
  6: "12:00 PM to 12.30 PM",
  7: "12:30 PM to 1.00 PM",
  8: "1:00 PM to 1.30 PM",
  9: "1:30 PM to 2.00 PM",
  10: "2:00 PM to 2.30 PM",
  11: "2:30 PM to 3.00 PM",
  12: "3:00 PM to 3.30 PM",
  13: "3:30 PM to 4.00 PM",
  14: "4:00 PM to 4.30 PM",
  15: "4:30 PM to 5.00 PM",
  16: "5:00 PM to 5.30 PM",
  17: "5:30 PM to 6.00 PM",
  18: "6:00 PM to 6.30 PM",
  19: "6:30 PM to 7.00 PM",
  20: "7:00 PM to 7.30 PM",
  21: "7:30 PM to 8.00 PM",
  22: "8:00 PM to 8.30 PM",
  23: "8:30 PM to 9.00 PM",
};
